/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 87
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 83
#define ALIAS_COUNT 0
#define TOKEN_COUNT 56
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  sym_keyword_table = 3,
  anon_sym_DOT = 4,
  aux_sym_column_token1 = 5,
  anon_sym_string = 6,
  anon_sym_text = 7,
  anon_sym_char = 8,
  anon_sym_varchar = 9,
  anon_sym_varchar2 = 10,
  anon_sym_tinyint = 11,
  anon_sym_int = 12,
  anon_sym_integer = 13,
  anon_sym_bigint = 14,
  anon_sym_float = 15,
  anon_sym_double = 16,
  anon_sym_decimal = 17,
  anon_sym_bool = 18,
  anon_sym_boolean = 19,
  anon_sym_json = 20,
  anon_sym_jsonb = 21,
  anon_sym_clob = 22,
  anon_sym_date = 23,
  anon_sym_time = 24,
  anon_sym_datetime = 25,
  anon_sym_timestamp = 26,
  anon_sym_nvarchar = 27,
  anon_sym_LBRACK = 28,
  anon_sym_RBRACK = 29,
  anon_sym_COMMA = 30,
  anon_sym_null = 31,
  anon_sym_notnull = 32,
  anon_sym_unique = 33,
  anon_sym_default = 34,
  anon_sym_increment = 35,
  anon_sym_PK = 36,
  anon_sym_pk = 37,
  aux_sym_length_token1 = 38,
  anon_sym_LPAREN = 39,
  anon_sym_RPAREN = 40,
  aux_sym_key_value_token1 = 41,
  sym_separate = 42,
  anon_sym_ref = 43,
  anon_sym_note = 44,
  anon_sym_Note = 45,
  anon_sym_as = 46,
  anon_sym_enum = 47,
  anon_sym_GT = 48,
  anon_sym_LT = 49,
  anon_sym_DASH = 50,
  anon_sym_LT_GT = 51,
  anon_sym_SQUOTE = 52,
  aux_sym__note_token1 = 53,
  anon_sym_BQUOTE = 54,
  anon_sym_LPAREN_RPAREN = 55,
  sym_source_file = 56,
  sym_table = 57,
  sym_table_name = 58,
  sym_schema = 59,
  sym_alias = 60,
  sym_body = 61,
  sym_column = 62,
  sym_identifier = 63,
  sym_type = 64,
  sym__basic_type = 65,
  sym__type_length = 66,
  sym_setting = 67,
  sym_setting_keys = 68,
  sym_setting_key = 69,
  sym_length = 70,
  sym_bracket = 71,
  sym_key_value = 72,
  sym_key = 73,
  sym_value = 74,
  sym_keyword = 75,
  sym__ref = 76,
  sym__note = 77,
  sym__default = 78,
  aux_sym_source_file_repeat1 = 79,
  aux_sym_table_repeat1 = 80,
  aux_sym_setting_repeat1 = 81,
  aux_sym_setting_keys_repeat1 = 82,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_keyword_table] = "keyword_table",
  [anon_sym_DOT] = ".",
  [aux_sym_column_token1] = "column_token1",
  [anon_sym_string] = "string",
  [anon_sym_text] = "text",
  [anon_sym_char] = "char",
  [anon_sym_varchar] = "varchar",
  [anon_sym_varchar2] = "varchar2",
  [anon_sym_tinyint] = "tinyint",
  [anon_sym_int] = "int",
  [anon_sym_integer] = "integer",
  [anon_sym_bigint] = "bigint",
  [anon_sym_float] = "float",
  [anon_sym_double] = "double",
  [anon_sym_decimal] = "decimal",
  [anon_sym_bool] = "bool",
  [anon_sym_boolean] = "boolean",
  [anon_sym_json] = "json",
  [anon_sym_jsonb] = "jsonb",
  [anon_sym_clob] = "clob",
  [anon_sym_date] = "date",
  [anon_sym_time] = "time",
  [anon_sym_datetime] = "datetime",
  [anon_sym_timestamp] = "timestamp",
  [anon_sym_nvarchar] = "nvarchar",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_null] = "null",
  [anon_sym_notnull] = "not null",
  [anon_sym_unique] = "unique",
  [anon_sym_default] = "default",
  [anon_sym_increment] = "increment",
  [anon_sym_PK] = "PK",
  [anon_sym_pk] = "pk",
  [aux_sym_length_token1] = "length_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_key_value_token1] = "key_value_token1",
  [sym_separate] = "separate",
  [anon_sym_ref] = "ref",
  [anon_sym_note] = "note",
  [anon_sym_Note] = "Note",
  [anon_sym_as] = "as",
  [anon_sym_enum] = "enum",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_DASH] = "-",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__note_token1] = "_note_token1",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_LPAREN_RPAREN] = "()",
  [sym_source_file] = "source_file",
  [sym_table] = "table",
  [sym_table_name] = "table_name",
  [sym_schema] = "schema",
  [sym_alias] = "alias",
  [sym_body] = "body",
  [sym_column] = "column",
  [sym_identifier] = "identifier",
  [sym_type] = "type",
  [sym__basic_type] = "_basic_type",
  [sym__type_length] = "_type_length",
  [sym_setting] = "setting",
  [sym_setting_keys] = "setting_keys",
  [sym_setting_key] = "setting_key",
  [sym_length] = "length",
  [sym_bracket] = "bracket",
  [sym_key_value] = "key_value",
  [sym_key] = "key",
  [sym_value] = "value",
  [sym_keyword] = "keyword",
  [sym__ref] = "_ref",
  [sym__note] = "_note",
  [sym__default] = "_default",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_table_repeat1] = "table_repeat1",
  [aux_sym_setting_repeat1] = "setting_repeat1",
  [aux_sym_setting_keys_repeat1] = "setting_keys_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_keyword_table] = sym_keyword_table,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_column_token1] = aux_sym_column_token1,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_text] = anon_sym_text,
  [anon_sym_char] = anon_sym_char,
  [anon_sym_varchar] = anon_sym_varchar,
  [anon_sym_varchar2] = anon_sym_varchar2,
  [anon_sym_tinyint] = anon_sym_tinyint,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_integer] = anon_sym_integer,
  [anon_sym_bigint] = anon_sym_bigint,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_double] = anon_sym_double,
  [anon_sym_decimal] = anon_sym_decimal,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_boolean] = anon_sym_boolean,
  [anon_sym_json] = anon_sym_json,
  [anon_sym_jsonb] = anon_sym_jsonb,
  [anon_sym_clob] = anon_sym_clob,
  [anon_sym_date] = anon_sym_date,
  [anon_sym_time] = anon_sym_time,
  [anon_sym_datetime] = anon_sym_datetime,
  [anon_sym_timestamp] = anon_sym_timestamp,
  [anon_sym_nvarchar] = anon_sym_nvarchar,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_notnull] = anon_sym_notnull,
  [anon_sym_unique] = anon_sym_unique,
  [anon_sym_default] = anon_sym_default,
  [anon_sym_increment] = anon_sym_increment,
  [anon_sym_PK] = anon_sym_PK,
  [anon_sym_pk] = anon_sym_pk,
  [aux_sym_length_token1] = aux_sym_length_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_key_value_token1] = aux_sym_key_value_token1,
  [sym_separate] = sym_separate,
  [anon_sym_ref] = anon_sym_ref,
  [anon_sym_note] = anon_sym_note,
  [anon_sym_Note] = anon_sym_Note,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__note_token1] = aux_sym__note_token1,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_LPAREN_RPAREN] = anon_sym_LPAREN_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym_table] = sym_table,
  [sym_table_name] = sym_table_name,
  [sym_schema] = sym_schema,
  [sym_alias] = sym_alias,
  [sym_body] = sym_body,
  [sym_column] = sym_column,
  [sym_identifier] = sym_identifier,
  [sym_type] = sym_type,
  [sym__basic_type] = sym__basic_type,
  [sym__type_length] = sym__type_length,
  [sym_setting] = sym_setting,
  [sym_setting_keys] = sym_setting_keys,
  [sym_setting_key] = sym_setting_key,
  [sym_length] = sym_length,
  [sym_bracket] = sym_bracket,
  [sym_key_value] = sym_key_value,
  [sym_key] = sym_key,
  [sym_value] = sym_value,
  [sym_keyword] = sym_keyword,
  [sym__ref] = sym__ref,
  [sym__note] = sym__note,
  [sym__default] = sym__default,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_table_repeat1] = aux_sym_table_repeat1,
  [aux_sym_setting_repeat1] = aux_sym_setting_repeat1,
  [aux_sym_setting_keys_repeat1] = aux_sym_setting_keys_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_keyword_table] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_column_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_text] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_varchar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_varchar2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tinyint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_integer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bigint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_double] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_decimal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boolean] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_json] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jsonb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_clob] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_date] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_time] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_datetime] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_timestamp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nvarchar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_notnull] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unique] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_default] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_increment] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pk] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_length_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_key_value_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_separate] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ref] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_note] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Note] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__note_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_table] = {
    .visible = true,
    .named = true,
  },
  [sym_table_name] = {
    .visible = true,
    .named = true,
  },
  [sym_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_column] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym__basic_type] = {
    .visible = false,
    .named = true,
  },
  [sym__type_length] = {
    .visible = false,
    .named = true,
  },
  [sym_setting] = {
    .visible = true,
    .named = true,
  },
  [sym_setting_keys] = {
    .visible = true,
    .named = true,
  },
  [sym_setting_key] = {
    .visible = true,
    .named = true,
  },
  [sym_length] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym__ref] = {
    .visible = false,
    .named = true,
  },
  [sym__note] = {
    .visible = false,
    .named = true,
  },
  [sym__default] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_setting_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_setting_keys_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 27,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 32,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 12,
  [43] = 43,
  [44] = 17,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 16,
  [51] = 18,
  [52] = 52,
  [53] = 19,
  [54] = 54,
  [55] = 20,
  [56] = 21,
  [57] = 57,
  [58] = 2,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 54,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 64,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 66,
  [78] = 68,
  [79] = 79,
  [80] = 74,
  [81] = 76,
  [82] = 82,
  [83] = 67,
  [84] = 73,
  [85] = 75,
  [86] = 69,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(120);
      ADVANCE_MAP(
        '\'', 173,
        '(', 160,
        ')', 161,
        ',', 150,
        '-', 171,
        '.', 124,
        ':', 163,
        '<', 170,
        '>', 169,
        'N', 82,
        'P', 5,
        'T', 6,
        '[', 148,
        ']', 149,
        '`', 175,
        'a', 99,
        'b', 47,
        'c', 44,
        'd', 8,
        'e', 75,
        'f', 59,
        'i', 71,
        'j', 100,
        'n', 88,
        'p', 54,
        'r', 26,
        's', 101,
        't', 27,
        'u', 72,
        'v', 7,
        '{', 121,
        '}', 122,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(158);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(78);
      if (lookahead == 'e') ADVANCE(165);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '(', 159,
        ')', 161,
        'N', 82,
        'P', 5,
        '[', 148,
        'd', 35,
        'i', 76,
        'n', 87,
        'p', 54,
        'r', 26,
        'u', 72,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == ':') ADVANCE(163);
      if (lookahead == '}') ADVANCE(122);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(176);
      END_STATE();
    case 5:
      if (lookahead == 'K') ADVANCE(156);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(91);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(110);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == 'o') ADVANCE(116);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(113);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(92);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(66);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(104);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(94);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(74);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(57);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(95);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(98);
      END_STATE();
    case 18:
      if (lookahead == 'b') ADVANCE(142);
      END_STATE();
    case 19:
      if (lookahead == 'b') ADVANCE(61);
      END_STATE();
    case 20:
      if (lookahead == 'b') ADVANCE(62);
      END_STATE();
    case 21:
      if (lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 22:
      if (lookahead == 'c') ADVANCE(49);
      if (lookahead == 'f') ADVANCE(9);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(96);
      END_STATE();
    case 24:
      if (lookahead == 'c') ADVANCE(96);
      if (lookahead == 't') ADVANCE(132);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(46);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(117);
      if (lookahead == 'i') ADVANCE(67);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(166);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(143);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(144);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(123);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(136);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(153);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(145);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(81);
      END_STATE();
    case 39:
      if (lookahead == 'f') ADVANCE(164);
      END_STATE();
    case 40:
      if (lookahead == 'f') ADVANCE(9);
      END_STATE();
    case 41:
      if (lookahead == 'g') ADVANCE(126);
      END_STATE();
    case 42:
      if (lookahead == 'g') ADVANCE(50);
      END_STATE();
    case 43:
      if (lookahead == 'g') ADVANCE(37);
      END_STATE();
    case 44:
      if (lookahead == 'h') ADVANCE(10);
      if (lookahead == 'l') ADVANCE(83);
      END_STATE();
    case 45:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 46:
      if (lookahead == 'h') ADVANCE(16);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(42);
      if (lookahead == 'o') ADVANCE(86);
      END_STATE();
    case 48:
      if (lookahead == 'i') ADVANCE(90);
      END_STATE();
    case 49:
      if (lookahead == 'i') ADVANCE(68);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(79);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(77);
      END_STATE();
    case 52:
      if (lookahead == 'i') ADVANCE(70);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(80);
      END_STATE();
    case 54:
      if (lookahead == 'k') ADVANCE(157);
      END_STATE();
    case 55:
      if (lookahead == 'l') ADVANCE(138);
      END_STATE();
    case 56:
      if (lookahead == 'l') ADVANCE(151);
      END_STATE();
    case 57:
      if (lookahead == 'l') ADVANCE(137);
      END_STATE();
    case 58:
      if (lookahead == 'l') ADVANCE(152);
      END_STATE();
    case 59:
      if (lookahead == 'l') ADVANCE(84);
      END_STATE();
    case 60:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 61:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 62:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 63:
      if (lookahead == 'l') ADVANCE(58);
      END_STATE();
    case 64:
      if (lookahead == 'l') ADVANCE(106);
      END_STATE();
    case 65:
      if (lookahead == 'm') ADVANCE(168);
      END_STATE();
    case 66:
      if (lookahead == 'm') ADVANCE(89);
      END_STATE();
    case 67:
      if (lookahead == 'm') ADVANCE(30);
      if (lookahead == 'n') ADVANCE(118);
      END_STATE();
    case 68:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 69:
      if (lookahead == 'm') ADVANCE(38);
      END_STATE();
    case 70:
      if (lookahead == 'm') ADVANCE(34);
      END_STATE();
    case 71:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 72:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 73:
      if (lookahead == 'n') ADVANCE(140);
      END_STATE();
    case 74:
      if (lookahead == 'n') ADVANCE(139);
      END_STATE();
    case 75:
      if (lookahead == 'n') ADVANCE(112);
      END_STATE();
    case 76:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 77:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(115);
      END_STATE();
    case 79:
      if (lookahead == 'n') ADVANCE(105);
      END_STATE();
    case 80:
      if (lookahead == 'n') ADVANCE(107);
      END_STATE();
    case 81:
      if (lookahead == 'n') ADVANCE(108);
      END_STATE();
    case 82:
      if (lookahead == 'o') ADVANCE(109);
      END_STATE();
    case 83:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 84:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 85:
      if (lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 86:
      if (lookahead == 'o') ADVANCE(55);
      END_STATE();
    case 87:
      if (lookahead == 'o') ADVANCE(102);
      if (lookahead == 'u') ADVANCE(60);
      END_STATE();
    case 88:
      if (lookahead == 'o') ADVANCE(102);
      if (lookahead == 'u') ADVANCE(60);
      if (lookahead == 'v') ADVANCE(17);
      END_STATE();
    case 89:
      if (lookahead == 'p') ADVANCE(146);
      END_STATE();
    case 90:
      if (lookahead == 'q') ADVANCE(114);
      END_STATE();
    case 91:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 92:
      if (lookahead == 'r') ADVANCE(128);
      END_STATE();
    case 93:
      if (lookahead == 'r') ADVANCE(133);
      END_STATE();
    case 94:
      if (lookahead == 'r') ADVANCE(129);
      END_STATE();
    case 95:
      if (lookahead == 'r') ADVANCE(147);
      END_STATE();
    case 96:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 97:
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 98:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 99:
      if (lookahead == 's') ADVANCE(167);
      END_STATE();
    case 100:
      if (lookahead == 's') ADVANCE(85);
      END_STATE();
    case 101:
      if (lookahead == 't') ADVANCE(97);
      END_STATE();
    case 102:
      if (lookahead == 't') ADVANCE(1);
      END_STATE();
    case 103:
      if (lookahead == 't') ADVANCE(127);
      END_STATE();
    case 104:
      if (lookahead == 't') ADVANCE(135);
      END_STATE();
    case 105:
      if (lookahead == 't') ADVANCE(134);
      END_STATE();
    case 106:
      if (lookahead == 't') ADVANCE(154);
      END_STATE();
    case 107:
      if (lookahead == 't') ADVANCE(131);
      END_STATE();
    case 108:
      if (lookahead == 't') ADVANCE(155);
      END_STATE();
    case 109:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 110:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 111:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 112:
      if (lookahead == 'u') ADVANCE(65);
      END_STATE();
    case 113:
      if (lookahead == 'u') ADVANCE(64);
      END_STATE();
    case 114:
      if (lookahead == 'u') ADVANCE(33);
      END_STATE();
    case 115:
      if (lookahead == 'u') ADVANCE(63);
      END_STATE();
    case 116:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 117:
      if (lookahead == 'x') ADVANCE(103);
      END_STATE();
    case 118:
      if (lookahead == 'y') ADVANCE(53);
      END_STATE();
    case 119:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(119);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(174);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_keyword_table);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(125);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_text);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_char);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_varchar);
      if (lookahead == '2') ADVANCE(130);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(anon_sym_varchar2);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(anon_sym_tinyint);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(anon_sym_int);
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(anon_sym_integer);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(anon_sym_bigint);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_double);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_decimal);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_bool);
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_boolean);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_json);
      if (lookahead == 'b') ADVANCE(141);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_jsonb);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_clob);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_date);
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_time);
      if (lookahead == 's') ADVANCE(111);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(anon_sym_datetime);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(anon_sym_timestamp);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(anon_sym_nvarchar);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_notnull);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(anon_sym_unique);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(anon_sym_default);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym_increment);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(anon_sym_PK);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(anon_sym_pk);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(aux_sym_length_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(158);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == ')') ADVANCE(176);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(aux_sym_key_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(162);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_separate);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(anon_sym_ref);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_note);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(anon_sym_Note);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '>') ADVANCE(172);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(aux_sym__note_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(174);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(anon_sym_LPAREN_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 119},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 162},
  [75] = {.lex_state = 162},
  [76] = {.lex_state = 119},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 162},
  [81] = {.lex_state = 119},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 162},
  [86] = {.lex_state = 119},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_keyword_table] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_text] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [anon_sym_varchar] = ACTIONS(1),
    [anon_sym_varchar2] = ACTIONS(1),
    [anon_sym_tinyint] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_integer] = ACTIONS(1),
    [anon_sym_bigint] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_double] = ACTIONS(1),
    [anon_sym_decimal] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_boolean] = ACTIONS(1),
    [anon_sym_json] = ACTIONS(1),
    [anon_sym_jsonb] = ACTIONS(1),
    [anon_sym_clob] = ACTIONS(1),
    [anon_sym_date] = ACTIONS(1),
    [anon_sym_time] = ACTIONS(1),
    [anon_sym_datetime] = ACTIONS(1),
    [anon_sym_timestamp] = ACTIONS(1),
    [anon_sym_nvarchar] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_notnull] = ACTIONS(1),
    [anon_sym_unique] = ACTIONS(1),
    [anon_sym_default] = ACTIONS(1),
    [anon_sym_increment] = ACTIONS(1),
    [anon_sym_PK] = ACTIONS(1),
    [anon_sym_pk] = ACTIONS(1),
    [aux_sym_length_token1] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_separate] = ACTIONS(1),
    [anon_sym_ref] = ACTIONS(1),
    [anon_sym_note] = ACTIONS(1),
    [anon_sym_Note] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(65),
    [sym_table] = STATE(31),
    [aux_sym_source_file_repeat1] = STATE(31),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_keyword_table] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(9), 6,
      anon_sym_varchar,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_json,
      anon_sym_date,
      anon_sym_time,
    ACTIONS(7), 28,
      anon_sym_string,
      anon_sym_text,
      anon_sym_char,
      anon_sym_varchar2,
      anon_sym_tinyint,
      anon_sym_integer,
      anon_sym_bigint,
      anon_sym_float,
      anon_sym_double,
      anon_sym_decimal,
      anon_sym_boolean,
      anon_sym_jsonb,
      anon_sym_clob,
      anon_sym_datetime,
      anon_sym_timestamp,
      anon_sym_nvarchar,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [39] = 6,
    ACTIONS(13), 1,
      anon_sym_varchar,
    ACTIONS(17), 1,
      anon_sym_nvarchar,
    STATE(7), 1,
      sym_type,
    STATE(22), 2,
      sym__basic_type,
      sym__type_length,
    ACTIONS(15), 5,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_json,
      anon_sym_date,
      anon_sym_time,
    ACTIONS(11), 15,
      anon_sym_string,
      anon_sym_text,
      anon_sym_char,
      anon_sym_varchar2,
      anon_sym_tinyint,
      anon_sym_integer,
      anon_sym_bigint,
      anon_sym_float,
      anon_sym_double,
      anon_sym_decimal,
      anon_sym_boolean,
      anon_sym_jsonb,
      anon_sym_clob,
      anon_sym_datetime,
      anon_sym_timestamp,
  [77] = 8,
    ACTIONS(19), 1,
      anon_sym_RBRACK,
    ACTIONS(23), 1,
      anon_sym_default,
    STATE(9), 1,
      sym_setting_key,
    STATE(17), 1,
      sym_key_value,
    STATE(84), 1,
      sym_key,
    STATE(5), 2,
      sym_setting_keys,
      aux_sym_setting_repeat1,
    ACTIONS(25), 3,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
    ACTIONS(21), 6,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
  [110] = 8,
    ACTIONS(23), 1,
      anon_sym_default,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    STATE(9), 1,
      sym_setting_key,
    STATE(17), 1,
      sym_key_value,
    STATE(84), 1,
      sym_key,
    STATE(6), 2,
      sym_setting_keys,
      aux_sym_setting_repeat1,
    ACTIONS(25), 3,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
    ACTIONS(21), 6,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
  [143] = 8,
    ACTIONS(29), 1,
      anon_sym_RBRACK,
    ACTIONS(34), 1,
      anon_sym_default,
    STATE(9), 1,
      sym_setting_key,
    STATE(17), 1,
      sym_key_value,
    STATE(84), 1,
      sym_key,
    STATE(6), 2,
      sym_setting_keys,
      aux_sym_setting_repeat1,
    ACTIONS(37), 3,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
    ACTIONS(31), 6,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
  [176] = 8,
    ACTIONS(40), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 1,
      anon_sym_default,
    STATE(44), 1,
      sym_key_value,
    STATE(52), 1,
      sym_setting,
    STATE(61), 1,
      sym_setting_key,
    STATE(73), 1,
      sym_key,
    ACTIONS(25), 3,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
    ACTIONS(42), 6,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
  [208] = 3,
    STATE(43), 1,
      sym_bracket,
    ACTIONS(48), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(46), 11,
      anon_sym_LBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [229] = 3,
    ACTIONS(52), 1,
      anon_sym_COMMA,
    STATE(11), 1,
      aux_sym_setting_keys_repeat1,
    ACTIONS(50), 11,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [249] = 6,
    ACTIONS(23), 1,
      anon_sym_default,
    STATE(15), 1,
      sym_setting_key,
    STATE(17), 1,
      sym_key_value,
    STATE(84), 1,
      sym_key,
    ACTIONS(25), 3,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
    ACTIONS(21), 6,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
  [275] = 3,
    ACTIONS(52), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_setting_keys_repeat1,
    ACTIONS(54), 11,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [295] = 2,
    ACTIONS(58), 1,
      sym_separate,
    ACTIONS(56), 12,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [313] = 3,
    ACTIONS(62), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_setting_keys_repeat1,
    ACTIONS(60), 11,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [333] = 1,
    ACTIONS(65), 12,
      anon_sym_LBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      aux_sym_length_token1,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [348] = 1,
    ACTIONS(60), 12,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [363] = 1,
    ACTIONS(67), 12,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [378] = 1,
    ACTIONS(56), 12,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [393] = 1,
    ACTIONS(69), 12,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [408] = 1,
    ACTIONS(71), 12,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [423] = 1,
    ACTIONS(73), 12,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [438] = 1,
    ACTIONS(75), 12,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [453] = 1,
    ACTIONS(77), 11,
      anon_sym_LBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [467] = 1,
    ACTIONS(79), 11,
      anon_sym_LBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [481] = 7,
    ACTIONS(81), 1,
      aux_sym_length_token1,
    ACTIONS(85), 1,
      anon_sym_LT,
    ACTIONS(87), 1,
      anon_sym_SQUOTE,
    ACTIONS(89), 1,
      anon_sym_BQUOTE,
    STATE(50), 1,
      sym_value,
    ACTIONS(83), 3,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_LT_GT,
    STATE(51), 3,
      sym__ref,
      sym__note,
      sym__default,
  [507] = 7,
    ACTIONS(91), 1,
      aux_sym_length_token1,
    ACTIONS(95), 1,
      anon_sym_LT,
    ACTIONS(97), 1,
      anon_sym_SQUOTE,
    ACTIONS(99), 1,
      anon_sym_BQUOTE,
    STATE(16), 1,
      sym_value,
    ACTIONS(93), 3,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_LT_GT,
    STATE(18), 3,
      sym__ref,
      sym__note,
      sym__default,
  [533] = 4,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    ACTIONS(103), 1,
      aux_sym_column_token1,
    STATE(3), 1,
      sym_column,
    STATE(28), 2,
      sym_body,
      aux_sym_table_repeat1,
  [547] = 4,
    ACTIONS(105), 1,
      anon_sym_LBRACE,
    ACTIONS(107), 1,
      anon_sym_DOT,
    STATE(41), 1,
      sym_keyword,
    ACTIONS(109), 2,
      anon_sym_as,
      anon_sym_enum,
  [561] = 4,
    ACTIONS(103), 1,
      aux_sym_column_token1,
    ACTIONS(111), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      sym_column,
    STATE(30), 2,
      sym_body,
      aux_sym_table_repeat1,
  [575] = 3,
    STATE(40), 1,
      sym_keyword,
    ACTIONS(109), 2,
      anon_sym_as,
      anon_sym_enum,
    ACTIONS(113), 2,
      anon_sym_LBRACE,
      anon_sym_DOT,
  [587] = 4,
    ACTIONS(115), 1,
      anon_sym_RBRACE,
    ACTIONS(117), 1,
      aux_sym_column_token1,
    STATE(3), 1,
      sym_column,
    STATE(30), 2,
      sym_body,
      aux_sym_table_repeat1,
  [601] = 3,
    ACTIONS(5), 1,
      sym_keyword_table,
    ACTIONS(120), 1,
      ts_builtin_sym_end,
    STATE(35), 2,
      sym_table,
      aux_sym_source_file_repeat1,
  [612] = 4,
    ACTIONS(122), 1,
      aux_sym_column_token1,
    STATE(33), 1,
      sym_identifier,
    STATE(78), 1,
      sym_table_name,
    STATE(82), 1,
      sym_schema,
  [625] = 3,
    ACTIONS(124), 1,
      anon_sym_DOT,
    STATE(41), 1,
      sym_keyword,
    ACTIONS(109), 2,
      anon_sym_as,
      anon_sym_enum,
  [636] = 1,
    ACTIONS(127), 4,
      anon_sym_LBRACE,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_enum,
  [643] = 3,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    ACTIONS(131), 1,
      sym_keyword_table,
    STATE(35), 2,
      sym_table,
      aux_sym_source_file_repeat1,
  [654] = 4,
    ACTIONS(122), 1,
      aux_sym_column_token1,
    STATE(27), 1,
      sym_identifier,
    STATE(72), 1,
      sym_table_name,
    STATE(82), 1,
      sym_schema,
  [667] = 4,
    ACTIONS(122), 1,
      aux_sym_column_token1,
    STATE(33), 1,
      sym_identifier,
    STATE(68), 1,
      sym_table_name,
    STATE(82), 1,
      sym_schema,
  [680] = 2,
    STATE(43), 1,
      sym_bracket,
    ACTIONS(48), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [688] = 2,
    STATE(23), 1,
      sym_bracket,
    ACTIONS(48), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [696] = 3,
    ACTIONS(122), 1,
      aux_sym_column_token1,
    STATE(47), 1,
      sym_identifier,
    STATE(48), 1,
      sym_alias,
  [706] = 3,
    ACTIONS(122), 1,
      aux_sym_column_token1,
    STATE(45), 1,
      sym_alias,
    STATE(47), 1,
      sym_identifier,
  [716] = 2,
    ACTIONS(58), 1,
      sym_separate,
    ACTIONS(56), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [724] = 2,
    ACTIONS(134), 1,
      aux_sym_length_token1,
    STATE(39), 1,
      sym_length,
  [731] = 1,
    ACTIONS(56), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [736] = 1,
    ACTIONS(113), 2,
      anon_sym_LBRACE,
      anon_sym_DOT,
  [741] = 1,
    ACTIONS(136), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [746] = 1,
    ACTIONS(138), 2,
      anon_sym_LBRACE,
      anon_sym_DOT,
  [751] = 1,
    ACTIONS(140), 2,
      anon_sym_LBRACE,
      anon_sym_DOT,
  [756] = 1,
    ACTIONS(142), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [761] = 1,
    ACTIONS(67), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [766] = 1,
    ACTIONS(69), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [771] = 1,
    ACTIONS(144), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [776] = 1,
    ACTIONS(71), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [781] = 2,
    ACTIONS(146), 1,
      aux_sym_column_token1,
    STATE(56), 1,
      sym_column,
  [788] = 1,
    ACTIONS(73), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [793] = 1,
    ACTIONS(75), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [798] = 1,
    ACTIONS(148), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [803] = 1,
    ACTIONS(7), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [808] = 2,
    ACTIONS(122), 1,
      aux_sym_column_token1,
    STATE(29), 1,
      sym_identifier,
  [815] = 1,
    ACTIONS(150), 2,
      ts_builtin_sym_end,
      sym_keyword_table,
  [820] = 1,
    ACTIONS(152), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [825] = 2,
    ACTIONS(103), 1,
      aux_sym_column_token1,
    STATE(21), 1,
      sym_column,
  [832] = 1,
    ACTIONS(154), 2,
      ts_builtin_sym_end,
      sym_keyword_table,
  [837] = 1,
    ACTIONS(156), 1,
      anon_sym_BQUOTE,
  [841] = 1,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
  [845] = 1,
    ACTIONS(160), 1,
      anon_sym_SQUOTE,
  [849] = 1,
    ACTIONS(162), 1,
      anon_sym_LPAREN_RPAREN,
  [853] = 1,
    ACTIONS(164), 1,
      anon_sym_DOT,
  [857] = 1,
    ACTIONS(166), 1,
      aux_sym__note_token1,
  [861] = 1,
    ACTIONS(168), 1,
      aux_sym_column_token1,
  [865] = 1,
    ACTIONS(170), 1,
      anon_sym_BQUOTE,
  [869] = 1,
    ACTIONS(172), 1,
      anon_sym_LBRACE,
  [873] = 1,
    ACTIONS(174), 1,
      sym_separate,
  [877] = 1,
    ACTIONS(176), 1,
      aux_sym_key_value_token1,
  [881] = 1,
    ACTIONS(178), 1,
      aux_sym_key_value_token1,
  [885] = 1,
    ACTIONS(180), 1,
      aux_sym__note_token1,
  [889] = 1,
    ACTIONS(182), 1,
      anon_sym_SQUOTE,
  [893] = 1,
    ACTIONS(184), 1,
      anon_sym_DOT,
  [897] = 1,
    ACTIONS(58), 1,
      sym_separate,
  [901] = 1,
    ACTIONS(186), 1,
      aux_sym_key_value_token1,
  [905] = 1,
    ACTIONS(188), 1,
      aux_sym__note_token1,
  [909] = 1,
    ACTIONS(190), 1,
      anon_sym_DOT,
  [913] = 1,
    ACTIONS(192), 1,
      anon_sym_LPAREN_RPAREN,
  [917] = 1,
    ACTIONS(194), 1,
      sym_separate,
  [921] = 1,
    ACTIONS(196), 1,
      aux_sym_key_value_token1,
  [925] = 1,
    ACTIONS(198), 1,
      aux_sym__note_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 77,
  [SMALL_STATE(5)] = 110,
  [SMALL_STATE(6)] = 143,
  [SMALL_STATE(7)] = 176,
  [SMALL_STATE(8)] = 208,
  [SMALL_STATE(9)] = 229,
  [SMALL_STATE(10)] = 249,
  [SMALL_STATE(11)] = 275,
  [SMALL_STATE(12)] = 295,
  [SMALL_STATE(13)] = 313,
  [SMALL_STATE(14)] = 333,
  [SMALL_STATE(15)] = 348,
  [SMALL_STATE(16)] = 363,
  [SMALL_STATE(17)] = 378,
  [SMALL_STATE(18)] = 393,
  [SMALL_STATE(19)] = 408,
  [SMALL_STATE(20)] = 423,
  [SMALL_STATE(21)] = 438,
  [SMALL_STATE(22)] = 453,
  [SMALL_STATE(23)] = 467,
  [SMALL_STATE(24)] = 481,
  [SMALL_STATE(25)] = 507,
  [SMALL_STATE(26)] = 533,
  [SMALL_STATE(27)] = 547,
  [SMALL_STATE(28)] = 561,
  [SMALL_STATE(29)] = 575,
  [SMALL_STATE(30)] = 587,
  [SMALL_STATE(31)] = 601,
  [SMALL_STATE(32)] = 612,
  [SMALL_STATE(33)] = 625,
  [SMALL_STATE(34)] = 636,
  [SMALL_STATE(35)] = 643,
  [SMALL_STATE(36)] = 654,
  [SMALL_STATE(37)] = 667,
  [SMALL_STATE(38)] = 680,
  [SMALL_STATE(39)] = 688,
  [SMALL_STATE(40)] = 696,
  [SMALL_STATE(41)] = 706,
  [SMALL_STATE(42)] = 716,
  [SMALL_STATE(43)] = 724,
  [SMALL_STATE(44)] = 731,
  [SMALL_STATE(45)] = 736,
  [SMALL_STATE(46)] = 741,
  [SMALL_STATE(47)] = 746,
  [SMALL_STATE(48)] = 751,
  [SMALL_STATE(49)] = 756,
  [SMALL_STATE(50)] = 761,
  [SMALL_STATE(51)] = 766,
  [SMALL_STATE(52)] = 771,
  [SMALL_STATE(53)] = 776,
  [SMALL_STATE(54)] = 781,
  [SMALL_STATE(55)] = 788,
  [SMALL_STATE(56)] = 793,
  [SMALL_STATE(57)] = 798,
  [SMALL_STATE(58)] = 803,
  [SMALL_STATE(59)] = 808,
  [SMALL_STATE(60)] = 815,
  [SMALL_STATE(61)] = 820,
  [SMALL_STATE(62)] = 825,
  [SMALL_STATE(63)] = 832,
  [SMALL_STATE(64)] = 837,
  [SMALL_STATE(65)] = 841,
  [SMALL_STATE(66)] = 845,
  [SMALL_STATE(67)] = 849,
  [SMALL_STATE(68)] = 853,
  [SMALL_STATE(69)] = 857,
  [SMALL_STATE(70)] = 861,
  [SMALL_STATE(71)] = 865,
  [SMALL_STATE(72)] = 869,
  [SMALL_STATE(73)] = 873,
  [SMALL_STATE(74)] = 877,
  [SMALL_STATE(75)] = 881,
  [SMALL_STATE(76)] = 885,
  [SMALL_STATE(77)] = 889,
  [SMALL_STATE(78)] = 893,
  [SMALL_STATE(79)] = 897,
  [SMALL_STATE(80)] = 901,
  [SMALL_STATE(81)] = 905,
  [SMALL_STATE(82)] = 909,
  [SMALL_STATE(83)] = 913,
  [SMALL_STATE(84)] = 917,
  [SMALL_STATE(85)] = 921,
  [SMALL_STATE(86)] = 925,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_column, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_setting_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_setting_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_setting_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_setting_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__basic_type, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting_keys, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting_keys, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting_key, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_setting_keys_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_setting_keys_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__note, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__default, 4, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ref, 5, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_length, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_table_name, 1, 0, 0), REDUCE(sym_schema, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 5, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_length, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 5, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [158] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dbdiagram(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dbdiagram",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
