/* Automatically @generated by tree-sitter v0.25.4 (726dcd1e872149d95de581589fc408fb8ea9cb0b) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 27
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  sym_keyword_table = 3,
  aux_sym_column_token1 = 4,
  anon_sym_bigint = 5,
  anon_sym_string = 6,
  anon_sym_timestamp = 7,
  anon_sym_int = 8,
  anon_sym_bool = 9,
  anon_sym_float = 10,
  anon_sym_varchar = 11,
  anon_sym_nvarchar = 12,
  anon_sym_LPAREN = 13,
  aux_sym_length_token1 = 14,
  anon_sym_RPAREN = 15,
  anon_sym_unique = 16,
  anon_sym_primarykey = 17,
  anon_sym_notnull = 18,
  anon_sym_null = 19,
  sym_source_file = 20,
  sym_table = 21,
  sym_table_name = 22,
  sym_body = 23,
  sym_column = 24,
  sym_identifier = 25,
  sym_type = 26,
  sym__basic_type = 27,
  sym__type_length = 28,
  sym_length = 29,
  sym_constrant = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_table_repeat1 = 32,
  aux_sym_body_repeat1 = 33,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_keyword_table] = "keyword_table",
  [aux_sym_column_token1] = "column_token1",
  [anon_sym_bigint] = "bigint",
  [anon_sym_string] = "string",
  [anon_sym_timestamp] = "timestamp",
  [anon_sym_int] = "int",
  [anon_sym_bool] = "bool",
  [anon_sym_float] = "float",
  [anon_sym_varchar] = "varchar",
  [anon_sym_nvarchar] = "nvarchar",
  [anon_sym_LPAREN] = "(",
  [aux_sym_length_token1] = "length_token1",
  [anon_sym_RPAREN] = ")",
  [anon_sym_unique] = "unique",
  [anon_sym_primarykey] = "primary key",
  [anon_sym_notnull] = "not null",
  [anon_sym_null] = "null",
  [sym_source_file] = "source_file",
  [sym_table] = "table",
  [sym_table_name] = "table_name",
  [sym_body] = "body",
  [sym_column] = "column",
  [sym_identifier] = "identifier",
  [sym_type] = "type",
  [sym__basic_type] = "_basic_type",
  [sym__type_length] = "_type_length",
  [sym_length] = "length",
  [sym_constrant] = "constrant",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_table_repeat1] = "table_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_keyword_table] = sym_keyword_table,
  [aux_sym_column_token1] = aux_sym_column_token1,
  [anon_sym_bigint] = anon_sym_bigint,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_timestamp] = anon_sym_timestamp,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_varchar] = anon_sym_varchar,
  [anon_sym_nvarchar] = anon_sym_nvarchar,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_length_token1] = aux_sym_length_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_unique] = anon_sym_unique,
  [anon_sym_primarykey] = anon_sym_primarykey,
  [anon_sym_notnull] = anon_sym_notnull,
  [anon_sym_null] = anon_sym_null,
  [sym_source_file] = sym_source_file,
  [sym_table] = sym_table,
  [sym_table_name] = sym_table_name,
  [sym_body] = sym_body,
  [sym_column] = sym_column,
  [sym_identifier] = sym_identifier,
  [sym_type] = sym_type,
  [sym__basic_type] = sym__basic_type,
  [sym__type_length] = sym__type_length,
  [sym_length] = sym_length,
  [sym_constrant] = sym_constrant,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_table_repeat1] = aux_sym_table_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_keyword_table] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_column_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_bigint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_timestamp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_varchar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nvarchar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_length_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unique] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_primarykey] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_notnull] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_table] = {
    .visible = true,
    .named = true,
  },
  [sym_table_name] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_column] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym__basic_type] = {
    .visible = false,
    .named = true,
  },
  [sym__type_length] = {
    .visible = false,
    .named = true,
  },
  [sym_length] = {
    .visible = true,
    .named = true,
  },
  [sym_constrant] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_parentheses = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_parentheses] = "parentheses",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_parentheses, 0},
    {field_parentheses, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(69);
      ADVANCE_MAP(
        '(', 99,
        ')', 101,
        'T', 4,
        'b', 23,
        'f', 33,
        'i', 40,
        'n', 46,
        'p', 55,
        's', 63,
        't', 24,
        'u', 41,
        'v', 5,
        '{', 70,
        '}', 71,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(43);
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(99);
      if (lookahead == 'n') ADVANCE(83);
      if (lookahead == 'p') ADVANCE(85);
      if (lookahead == 'u') ADVANCE(82);
      if (lookahead == '}') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(50);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(51);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(52);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(60);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(34);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(21);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(102);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 19:
      if (lookahead == 'g') ADVANCE(92);
      END_STATE();
    case 20:
      if (lookahead == 'g') ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead == 'h') ADVANCE(8);
      END_STATE();
    case 22:
      if (lookahead == 'h') ADVANCE(10);
      END_STATE();
    case 23:
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == 'o') ADVANCE(47);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 26:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 27:
      if (lookahead == 'i') ADVANCE(42);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(44);
      END_STATE();
    case 29:
      if (lookahead == 'k') ADVANCE(18);
      END_STATE();
    case 30:
      if (lookahead == 'l') ADVANCE(95);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(106);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(105);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(45);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 37:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 38:
      if (lookahead == 'm') ADVANCE(48);
      END_STATE();
    case 39:
      if (lookahead == 'm') ADVANCE(6);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 44:
      if (lookahead == 'n') ADVANCE(61);
      END_STATE();
    case 45:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 46:
      if (lookahead == 'o') ADVANCE(59);
      if (lookahead == 'u') ADVANCE(35);
      if (lookahead == 'v') ADVANCE(11);
      END_STATE();
    case 47:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 48:
      if (lookahead == 'p') ADVANCE(93);
      END_STATE();
    case 49:
      if (lookahead == 'q') ADVANCE(64);
      END_STATE();
    case 50:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 51:
      if (lookahead == 'r') ADVANCE(67);
      END_STATE();
    case 52:
      if (lookahead == 'r') ADVANCE(97);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(98);
      END_STATE();
    case 54:
      if (lookahead == 'r') ADVANCE(27);
      END_STATE();
    case 55:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 56:
      if (lookahead == 'r') ADVANCE(14);
      END_STATE();
    case 57:
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(94);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(2);
      END_STATE();
    case 60:
      if (lookahead == 't') ADVANCE(96);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(91);
      END_STATE();
    case 62:
      if (lookahead == 't') ADVANCE(7);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(54);
      END_STATE();
    case 64:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 65:
      if (lookahead == 'u') ADVANCE(36);
      END_STATE();
    case 66:
      if (lookahead == 'y') ADVANCE(104);
      END_STATE();
    case 67:
      if (lookahead == 'y') ADVANCE(1);
      END_STATE();
    case 68:
      if (lookahead == '}') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(68);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_keyword_table);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == ' ') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == ' ') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'a') ADVANCE(86);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'e') ADVANCE(103);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'i') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'i') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'l') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'l') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'm') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'n') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'o') ADVANCE(87);
      if (lookahead == 'u') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'q') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'r') ADVANCE(77);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'r') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 't') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'u') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'y') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_bigint);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_timestamp);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_varchar);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_nvarchar);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_length_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_unique);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_unique);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_primarykey);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_notnull);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 68},
  [13] = {.lex_state = 68},
  [14] = {.lex_state = 68},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 68},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_keyword_table] = ACTIONS(1),
    [anon_sym_bigint] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_timestamp] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_varchar] = ACTIONS(1),
    [anon_sym_nvarchar] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [aux_sym_length_token1] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_unique] = ACTIONS(1),
    [anon_sym_primarykey] = ACTIONS(1),
    [anon_sym_notnull] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(23),
    [sym_table] = STATE(15),
    [aux_sym_source_file_repeat1] = STATE(15),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_keyword_table] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(9), 1,
      anon_sym_varchar,
    ACTIONS(11), 1,
      anon_sym_nvarchar,
    STATE(6), 1,
      sym_type,
    STATE(10), 2,
      sym__basic_type,
      sym__type_length,
    ACTIONS(7), 6,
      anon_sym_bigint,
      anon_sym_string,
      anon_sym_timestamp,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_float,
  [22] = 1,
    ACTIONS(13), 8,
      anon_sym_bigint,
      anon_sym_string,
      anon_sym_timestamp,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_float,
      anon_sym_varchar,
      anon_sym_nvarchar,
  [33] = 5,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      aux_sym_column_token1,
    ACTIONS(19), 2,
      anon_sym_unique,
      anon_sym_null,
    ACTIONS(22), 2,
      anon_sym_primarykey,
      anon_sym_notnull,
    STATE(4), 2,
      sym_constrant,
      aux_sym_body_repeat1,
  [52] = 4,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_length,
    ACTIONS(25), 3,
      anon_sym_RBRACE,
      anon_sym_primarykey,
      anon_sym_notnull,
    ACTIONS(27), 3,
      aux_sym_column_token1,
      anon_sym_unique,
      anon_sym_null,
  [69] = 5,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(33), 1,
      aux_sym_column_token1,
    ACTIONS(35), 2,
      anon_sym_unique,
      anon_sym_null,
    ACTIONS(37), 2,
      anon_sym_primarykey,
      anon_sym_notnull,
    STATE(7), 2,
      sym_constrant,
      aux_sym_body_repeat1,
  [88] = 5,
    ACTIONS(39), 1,
      anon_sym_RBRACE,
    ACTIONS(41), 1,
      aux_sym_column_token1,
    ACTIONS(35), 2,
      anon_sym_unique,
      anon_sym_null,
    ACTIONS(37), 2,
      anon_sym_primarykey,
      anon_sym_notnull,
    STATE(4), 2,
      sym_constrant,
      aux_sym_body_repeat1,
  [107] = 2,
    ACTIONS(43), 3,
      anon_sym_RBRACE,
      anon_sym_primarykey,
      anon_sym_notnull,
    ACTIONS(45), 3,
      aux_sym_column_token1,
      anon_sym_unique,
      anon_sym_null,
  [118] = 2,
    ACTIONS(47), 3,
      anon_sym_RBRACE,
      anon_sym_primarykey,
      anon_sym_notnull,
    ACTIONS(49), 3,
      aux_sym_column_token1,
      anon_sym_unique,
      anon_sym_null,
  [129] = 2,
    ACTIONS(51), 3,
      anon_sym_RBRACE,
      anon_sym_primarykey,
      anon_sym_notnull,
    ACTIONS(53), 3,
      aux_sym_column_token1,
      anon_sym_unique,
      anon_sym_null,
  [140] = 2,
    ACTIONS(55), 3,
      anon_sym_RBRACE,
      anon_sym_primarykey,
      anon_sym_notnull,
    ACTIONS(57), 3,
      aux_sym_column_token1,
      anon_sym_unique,
      anon_sym_null,
  [151] = 4,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    ACTIONS(61), 1,
      aux_sym_column_token1,
    STATE(2), 1,
      sym_column,
    STATE(14), 2,
      sym_body,
      aux_sym_table_repeat1,
  [165] = 4,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    ACTIONS(65), 1,
      aux_sym_column_token1,
    STATE(2), 1,
      sym_column,
    STATE(13), 2,
      sym_body,
      aux_sym_table_repeat1,
  [179] = 4,
    ACTIONS(61), 1,
      aux_sym_column_token1,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(2), 1,
      sym_column,
    STATE(13), 2,
      sym_body,
      aux_sym_table_repeat1,
  [193] = 3,
    ACTIONS(5), 1,
      sym_keyword_table,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    STATE(16), 2,
      sym_table,
      aux_sym_source_file_repeat1,
  [204] = 3,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 1,
      sym_keyword_table,
    STATE(16), 2,
      sym_table,
      aux_sym_source_file_repeat1,
  [215] = 3,
    ACTIONS(77), 1,
      aux_sym_column_token1,
    STATE(21), 1,
      sym_identifier,
    STATE(22), 1,
      sym_table_name,
  [225] = 1,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      sym_keyword_table,
  [230] = 1,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      sym_keyword_table,
  [235] = 2,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    STATE(9), 1,
      sym_length,
  [242] = 1,
    ACTIONS(83), 1,
      anon_sym_LBRACE,
  [246] = 1,
    ACTIONS(85), 1,
      anon_sym_LBRACE,
  [250] = 1,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
  [254] = 1,
    ACTIONS(89), 1,
      anon_sym_LBRACE,
  [258] = 1,
    ACTIONS(91), 1,
      aux_sym_length_token1,
  [262] = 1,
    ACTIONS(93), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 22,
  [SMALL_STATE(4)] = 33,
  [SMALL_STATE(5)] = 52,
  [SMALL_STATE(6)] = 69,
  [SMALL_STATE(7)] = 88,
  [SMALL_STATE(8)] = 107,
  [SMALL_STATE(9)] = 118,
  [SMALL_STATE(10)] = 129,
  [SMALL_STATE(11)] = 140,
  [SMALL_STATE(12)] = 151,
  [SMALL_STATE(13)] = 165,
  [SMALL_STATE(14)] = 179,
  [SMALL_STATE(15)] = 193,
  [SMALL_STATE(16)] = 204,
  [SMALL_STATE(17)] = 215,
  [SMALL_STATE(18)] = 225,
  [SMALL_STATE(19)] = 230,
  [SMALL_STATE(20)] = 235,
  [SMALL_STATE(21)] = 242,
  [SMALL_STATE(22)] = 246,
  [SMALL_STATE(23)] = 250,
  [SMALL_STATE(24)] = 254,
  [SMALL_STATE(25)] = 258,
  [SMALL_STATE(26)] = 262,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__basic_type, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__basic_type, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constrant, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constrant, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_length, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type_length, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_length, 3, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_length, 3, 0, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 5, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [87] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dbdiagram(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dbdiagram",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
