/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 90
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 84
#define ALIAS_COUNT 0
#define TOKEN_COUNT 57
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  sym_keyword_table = 3,
  anon_sym_DOT = 4,
  aux_sym_column_token1 = 5,
  anon_sym_string = 6,
  anon_sym_text = 7,
  anon_sym_char = 8,
  anon_sym_varchar = 9,
  anon_sym_varchar2 = 10,
  anon_sym_tinyint = 11,
  anon_sym_int = 12,
  anon_sym_integer = 13,
  anon_sym_bigint = 14,
  anon_sym_float = 15,
  anon_sym_double = 16,
  anon_sym_decimal = 17,
  anon_sym_bool = 18,
  anon_sym_boolean = 19,
  anon_sym_json = 20,
  anon_sym_jsonb = 21,
  anon_sym_clob = 22,
  anon_sym_date = 23,
  anon_sym_time = 24,
  anon_sym_datetime = 25,
  anon_sym_timestamp = 26,
  anon_sym_nvarchar = 27,
  anon_sym_COMMA = 28,
  anon_sym_LBRACK = 29,
  anon_sym_RBRACK = 30,
  anon_sym_null = 31,
  anon_sym_notnull = 32,
  anon_sym_unique = 33,
  anon_sym_default = 34,
  anon_sym_increment = 35,
  anon_sym_PK = 36,
  anon_sym_pk = 37,
  anon_sym_primarykey = 38,
  aux_sym_length_token1 = 39,
  anon_sym_LPAREN = 40,
  anon_sym_RPAREN = 41,
  aux_sym_key_value_token1 = 42,
  sym_separate = 43,
  anon_sym_ref = 44,
  anon_sym_note = 45,
  anon_sym_Note = 46,
  anon_sym_as = 47,
  anon_sym_enum = 48,
  anon_sym_GT = 49,
  anon_sym_LT = 50,
  anon_sym_DASH = 51,
  anon_sym_LT_GT = 52,
  anon_sym_SQUOTE = 53,
  aux_sym__note_token1 = 54,
  anon_sym_BQUOTE = 55,
  anon_sym_LPAREN_RPAREN = 56,
  sym_source_file = 57,
  sym_table = 58,
  sym_table_name = 59,
  sym_schema = 60,
  sym_alias = 61,
  sym_body = 62,
  sym_column = 63,
  sym_identifier = 64,
  sym_type = 65,
  sym__basic_type = 66,
  sym__type_length = 67,
  sym_setting = 68,
  sym_setting_keys = 69,
  sym_setting_key = 70,
  sym_length = 71,
  sym_bracket = 72,
  sym_key_value = 73,
  sym_key = 74,
  sym_value = 75,
  sym_keyword = 76,
  sym__ref = 77,
  sym__note = 78,
  sym__default = 79,
  aux_sym_source_file_repeat1 = 80,
  aux_sym_table_repeat1 = 81,
  aux_sym_setting_repeat1 = 82,
  aux_sym_setting_keys_repeat1 = 83,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_keyword_table] = "keyword_table",
  [anon_sym_DOT] = ".",
  [aux_sym_column_token1] = "column_token1",
  [anon_sym_string] = "string",
  [anon_sym_text] = "text",
  [anon_sym_char] = "char",
  [anon_sym_varchar] = "varchar",
  [anon_sym_varchar2] = "varchar2",
  [anon_sym_tinyint] = "tinyint",
  [anon_sym_int] = "int",
  [anon_sym_integer] = "integer",
  [anon_sym_bigint] = "bigint",
  [anon_sym_float] = "float",
  [anon_sym_double] = "double",
  [anon_sym_decimal] = "decimal",
  [anon_sym_bool] = "bool",
  [anon_sym_boolean] = "boolean",
  [anon_sym_json] = "json",
  [anon_sym_jsonb] = "jsonb",
  [anon_sym_clob] = "clob",
  [anon_sym_date] = "date",
  [anon_sym_time] = "time",
  [anon_sym_datetime] = "datetime",
  [anon_sym_timestamp] = "timestamp",
  [anon_sym_nvarchar] = "nvarchar",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_null] = "null",
  [anon_sym_notnull] = "not null",
  [anon_sym_unique] = "unique",
  [anon_sym_default] = "default",
  [anon_sym_increment] = "increment",
  [anon_sym_PK] = "PK",
  [anon_sym_pk] = "pk",
  [anon_sym_primarykey] = "primary key",
  [aux_sym_length_token1] = "length_token1",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [aux_sym_key_value_token1] = "key_value_token1",
  [sym_separate] = "separate",
  [anon_sym_ref] = "ref",
  [anon_sym_note] = "note",
  [anon_sym_Note] = "Note",
  [anon_sym_as] = "as",
  [anon_sym_enum] = "enum",
  [anon_sym_GT] = ">",
  [anon_sym_LT] = "<",
  [anon_sym_DASH] = "-",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_SQUOTE] = "'",
  [aux_sym__note_token1] = "_note_token1",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_LPAREN_RPAREN] = "()",
  [sym_source_file] = "source_file",
  [sym_table] = "table",
  [sym_table_name] = "table_name",
  [sym_schema] = "schema",
  [sym_alias] = "alias",
  [sym_body] = "body",
  [sym_column] = "column",
  [sym_identifier] = "identifier",
  [sym_type] = "type",
  [sym__basic_type] = "_basic_type",
  [sym__type_length] = "_type_length",
  [sym_setting] = "setting",
  [sym_setting_keys] = "setting_keys",
  [sym_setting_key] = "setting_key",
  [sym_length] = "length",
  [sym_bracket] = "bracket",
  [sym_key_value] = "key_value",
  [sym_key] = "key",
  [sym_value] = "value",
  [sym_keyword] = "keyword",
  [sym__ref] = "_ref",
  [sym__note] = "_note",
  [sym__default] = "_default",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_table_repeat1] = "table_repeat1",
  [aux_sym_setting_repeat1] = "setting_repeat1",
  [aux_sym_setting_keys_repeat1] = "setting_keys_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_keyword_table] = sym_keyword_table,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym_column_token1] = aux_sym_column_token1,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_text] = anon_sym_text,
  [anon_sym_char] = anon_sym_char,
  [anon_sym_varchar] = anon_sym_varchar,
  [anon_sym_varchar2] = anon_sym_varchar2,
  [anon_sym_tinyint] = anon_sym_tinyint,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_integer] = anon_sym_integer,
  [anon_sym_bigint] = anon_sym_bigint,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_double] = anon_sym_double,
  [anon_sym_decimal] = anon_sym_decimal,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_boolean] = anon_sym_boolean,
  [anon_sym_json] = anon_sym_json,
  [anon_sym_jsonb] = anon_sym_jsonb,
  [anon_sym_clob] = anon_sym_clob,
  [anon_sym_date] = anon_sym_date,
  [anon_sym_time] = anon_sym_time,
  [anon_sym_datetime] = anon_sym_datetime,
  [anon_sym_timestamp] = anon_sym_timestamp,
  [anon_sym_nvarchar] = anon_sym_nvarchar,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_notnull] = anon_sym_notnull,
  [anon_sym_unique] = anon_sym_unique,
  [anon_sym_default] = anon_sym_default,
  [anon_sym_increment] = anon_sym_increment,
  [anon_sym_PK] = anon_sym_PK,
  [anon_sym_pk] = anon_sym_pk,
  [anon_sym_primarykey] = anon_sym_primarykey,
  [aux_sym_length_token1] = aux_sym_length_token1,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [aux_sym_key_value_token1] = aux_sym_key_value_token1,
  [sym_separate] = sym_separate,
  [anon_sym_ref] = anon_sym_ref,
  [anon_sym_note] = anon_sym_note,
  [anon_sym_Note] = anon_sym_Note,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym__note_token1] = aux_sym__note_token1,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_LPAREN_RPAREN] = anon_sym_LPAREN_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym_table] = sym_table,
  [sym_table_name] = sym_table_name,
  [sym_schema] = sym_schema,
  [sym_alias] = sym_alias,
  [sym_body] = sym_body,
  [sym_column] = sym_column,
  [sym_identifier] = sym_identifier,
  [sym_type] = sym_type,
  [sym__basic_type] = sym__basic_type,
  [sym__type_length] = sym__type_length,
  [sym_setting] = sym_setting,
  [sym_setting_keys] = sym_setting_keys,
  [sym_setting_key] = sym_setting_key,
  [sym_length] = sym_length,
  [sym_bracket] = sym_bracket,
  [sym_key_value] = sym_key_value,
  [sym_key] = sym_key,
  [sym_value] = sym_value,
  [sym_keyword] = sym_keyword,
  [sym__ref] = sym__ref,
  [sym__note] = sym__note,
  [sym__default] = sym__default,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_table_repeat1] = aux_sym_table_repeat1,
  [aux_sym_setting_repeat1] = aux_sym_setting_repeat1,
  [aux_sym_setting_keys_repeat1] = aux_sym_setting_keys_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_keyword_table] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_column_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_text] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_char] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_varchar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_varchar2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tinyint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_integer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bigint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_double] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_decimal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boolean] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_json] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_jsonb] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_clob] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_date] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_time] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_datetime] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_timestamp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nvarchar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_notnull] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_unique] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_default] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_increment] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pk] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_primarykey] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_length_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_key_value_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_separate] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ref] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_note] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Note] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__note_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_table] = {
    .visible = true,
    .named = true,
  },
  [sym_table_name] = {
    .visible = true,
    .named = true,
  },
  [sym_schema] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_column] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym__basic_type] = {
    .visible = false,
    .named = true,
  },
  [sym__type_length] = {
    .visible = false,
    .named = true,
  },
  [sym_setting] = {
    .visible = true,
    .named = true,
  },
  [sym_setting_keys] = {
    .visible = true,
    .named = true,
  },
  [sym_setting_key] = {
    .visible = true,
    .named = true,
  },
  [sym_length] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym__ref] = {
    .visible = false,
    .named = true,
  },
  [sym__note] = {
    .visible = false,
    .named = true,
  },
  [sym__default] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_table_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_setting_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_setting_keys_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 27,
  [36] = 32,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 15,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 20,
  [50] = 50,
  [51] = 18,
  [52] = 21,
  [53] = 53,
  [54] = 22,
  [55] = 55,
  [56] = 23,
  [57] = 24,
  [58] = 58,
  [59] = 2,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 55,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 71,
  [81] = 75,
  [82] = 78,
  [83] = 77,
  [84] = 76,
  [85] = 85,
  [86] = 73,
  [87] = 70,
  [88] = 69,
  [89] = 79,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(124);
      ADVANCE_MAP(
        '\'', 224,
        '(', 208,
        ')', 209,
        ',', 189,
        '-', 222,
        '.', 128,
        ':', 211,
        '<', 221,
        '>', 220,
        'N', 84,
        'P', 6,
        'T', 7,
        '[', 190,
        ']', 191,
        '`', 226,
        'a', 101,
        'b', 47,
        'c', 44,
        'd', 9,
        'e', 77,
        'f', 61,
        'i', 74,
        'j', 102,
        'n', 89,
        'p', 55,
        'r', 27,
        's', 103,
        't', 28,
        'u', 78,
        'v', 8,
        '{', 125,
        '}', 126,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(206);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(56);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(80);
      if (lookahead == 'e') ADVANCE(214);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '(', 207,
        ')', 209,
        ',', 189,
        'N', 154,
        'P', 131,
        '[', 190,
        'd', 135,
        'i', 151,
        'n', 155,
        'p', 145,
        'r', 138,
        'u', 152,
        '}', 126,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(206);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 4:
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ':') ADVANCE(211);
      if (lookahead == '}') ADVANCE(126);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 5:
      if (lookahead == ')') ADVANCE(227);
      END_STATE();
    case 6:
      if (lookahead == 'K') ADVANCE(201);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(92);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(112);
      if (lookahead == 'e') ADVANCE(25);
      if (lookahead == 'o') ADVANCE(118);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(115);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(93);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(97);
      END_STATE();
    case 13:
      if (lookahead == 'a') ADVANCE(68);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(106);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(76);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(59);
      END_STATE();
    case 17:
      if (lookahead == 'a') ADVANCE(95);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(96);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(100);
      END_STATE();
    case 20:
      if (lookahead == 'b') ADVANCE(183);
      END_STATE();
    case 21:
      if (lookahead == 'b') ADVANCE(63);
      END_STATE();
    case 22:
      if (lookahead == 'b') ADVANCE(64);
      END_STATE();
    case 23:
      if (lookahead == 'c') ADVANCE(45);
      END_STATE();
    case 24:
      if (lookahead == 'c') ADVANCE(98);
      if (lookahead == 't') ADVANCE(173);
      END_STATE();
    case 25:
      if (lookahead == 'c') ADVANCE(50);
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 26:
      if (lookahead == 'c') ADVANCE(46);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(119);
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(216);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(184);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(185);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(127);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(177);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(195);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(186);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(121);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 40:
      if (lookahead == 'f') ADVANCE(212);
      END_STATE();
    case 41:
      if (lookahead == 'g') ADVANCE(167);
      END_STATE();
    case 42:
      if (lookahead == 'g') ADVANCE(51);
      END_STATE();
    case 43:
      if (lookahead == 'g') ADVANCE(38);
      END_STATE();
    case 44:
      if (lookahead == 'h') ADVANCE(11);
      if (lookahead == 'l') ADVANCE(85);
      END_STATE();
    case 45:
      if (lookahead == 'h') ADVANCE(17);
      END_STATE();
    case 46:
      if (lookahead == 'h') ADVANCE(18);
      END_STATE();
    case 47:
      if (lookahead == 'i') ADVANCE(42);
      if (lookahead == 'o') ADVANCE(88);
      END_STATE();
    case 48:
      if (lookahead == 'i') ADVANCE(91);
      END_STATE();
    case 49:
      if (lookahead == 'i') ADVANCE(73);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(70);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(81);
      END_STATE();
    case 52:
      if (lookahead == 'i') ADVANCE(79);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 54:
      if (lookahead == 'i') ADVANCE(82);
      END_STATE();
    case 55:
      if (lookahead == 'k') ADVANCE(203);
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 56:
      if (lookahead == 'k') ADVANCE(36);
      END_STATE();
    case 57:
      if (lookahead == 'l') ADVANCE(179);
      END_STATE();
    case 58:
      if (lookahead == 'l') ADVANCE(192);
      END_STATE();
    case 59:
      if (lookahead == 'l') ADVANCE(178);
      END_STATE();
    case 60:
      if (lookahead == 'l') ADVANCE(194);
      END_STATE();
    case 61:
      if (lookahead == 'l') ADVANCE(86);
      END_STATE();
    case 62:
      if (lookahead == 'l') ADVANCE(58);
      END_STATE();
    case 63:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 64:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 66:
      if (lookahead == 'l') ADVANCE(108);
      END_STATE();
    case 67:
      if (lookahead == 'm') ADVANCE(219);
      END_STATE();
    case 68:
      if (lookahead == 'm') ADVANCE(90);
      END_STATE();
    case 69:
      if (lookahead == 'm') ADVANCE(31);
      if (lookahead == 'n') ADVANCE(122);
      END_STATE();
    case 70:
      if (lookahead == 'm') ADVANCE(16);
      END_STATE();
    case 71:
      if (lookahead == 'm') ADVANCE(39);
      END_STATE();
    case 72:
      if (lookahead == 'm') ADVANCE(35);
      END_STATE();
    case 73:
      if (lookahead == 'm') ADVANCE(12);
      END_STATE();
    case 74:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 75:
      if (lookahead == 'n') ADVANCE(181);
      END_STATE();
    case 76:
      if (lookahead == 'n') ADVANCE(180);
      END_STATE();
    case 77:
      if (lookahead == 'n') ADVANCE(114);
      END_STATE();
    case 78:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 79:
      if (lookahead == 'n') ADVANCE(41);
      END_STATE();
    case 80:
      if (lookahead == 'n') ADVANCE(117);
      END_STATE();
    case 81:
      if (lookahead == 'n') ADVANCE(107);
      END_STATE();
    case 82:
      if (lookahead == 'n') ADVANCE(109);
      END_STATE();
    case 83:
      if (lookahead == 'n') ADVANCE(110);
      END_STATE();
    case 84:
      if (lookahead == 'o') ADVANCE(111);
      END_STATE();
    case 85:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 86:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 87:
      if (lookahead == 'o') ADVANCE(75);
      END_STATE();
    case 88:
      if (lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 89:
      if (lookahead == 'o') ADVANCE(104);
      if (lookahead == 'u') ADVANCE(62);
      if (lookahead == 'v') ADVANCE(19);
      END_STATE();
    case 90:
      if (lookahead == 'p') ADVANCE(187);
      END_STATE();
    case 91:
      if (lookahead == 'q') ADVANCE(116);
      END_STATE();
    case 92:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 93:
      if (lookahead == 'r') ADVANCE(169);
      END_STATE();
    case 94:
      if (lookahead == 'r') ADVANCE(174);
      END_STATE();
    case 95:
      if (lookahead == 'r') ADVANCE(170);
      END_STATE();
    case 96:
      if (lookahead == 'r') ADVANCE(188);
      END_STATE();
    case 97:
      if (lookahead == 'r') ADVANCE(120);
      END_STATE();
    case 98:
      if (lookahead == 'r') ADVANCE(37);
      END_STATE();
    case 99:
      if (lookahead == 'r') ADVANCE(52);
      END_STATE();
    case 100:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 101:
      if (lookahead == 's') ADVANCE(218);
      END_STATE();
    case 102:
      if (lookahead == 's') ADVANCE(87);
      END_STATE();
    case 103:
      if (lookahead == 't') ADVANCE(99);
      END_STATE();
    case 104:
      if (lookahead == 't') ADVANCE(2);
      END_STATE();
    case 105:
      if (lookahead == 't') ADVANCE(168);
      END_STATE();
    case 106:
      if (lookahead == 't') ADVANCE(176);
      END_STATE();
    case 107:
      if (lookahead == 't') ADVANCE(175);
      END_STATE();
    case 108:
      if (lookahead == 't') ADVANCE(197);
      END_STATE();
    case 109:
      if (lookahead == 't') ADVANCE(172);
      END_STATE();
    case 110:
      if (lookahead == 't') ADVANCE(199);
      END_STATE();
    case 111:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 112:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 113:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 114:
      if (lookahead == 'u') ADVANCE(67);
      END_STATE();
    case 115:
      if (lookahead == 'u') ADVANCE(66);
      END_STATE();
    case 116:
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 117:
      if (lookahead == 'u') ADVANCE(65);
      END_STATE();
    case 118:
      if (lookahead == 'u') ADVANCE(22);
      END_STATE();
    case 119:
      if (lookahead == 'x') ADVANCE(105);
      END_STATE();
    case 120:
      if (lookahead == 'y') ADVANCE(1);
      END_STATE();
    case 121:
      if (lookahead == 'y') ADVANCE(205);
      END_STATE();
    case 122:
      if (lookahead == 'y') ADVANCE(54);
      END_STATE();
    case 123:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(225);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_keyword_table);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == ' ') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == ' ') ADVANCE(80);
      if (lookahead == 'e') ADVANCE(215);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'K') ADVANCE(202);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'a') ADVANCE(163);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'a') ADVANCE(157);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'c') ADVANCE(158);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'e') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'e') ADVANCE(217);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'e') ADVANCE(196);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'e') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'e') ADVANCE(150);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'e') ADVANCE(153);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'f') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'f') ADVANCE(213);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'i') ADVANCE(149);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'i') ADVANCE(156);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'k') ADVANCE(204);
      if (lookahead == 'r') ADVANCE(143);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'l') ADVANCE(193);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'l') ADVANCE(146);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'l') ADVANCE(160);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'm') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'm') ADVANCE(140);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'n') ADVANCE(134);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'n') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'n') ADVANCE(161);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'o') ADVANCE(162);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'o') ADVANCE(159);
      if (lookahead == 'u') ADVANCE(147);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'q') ADVANCE(164);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'r') ADVANCE(165);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'r') ADVANCE(139);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 't') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 't') ADVANCE(198);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 't') ADVANCE(200);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 't') ADVANCE(136);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'u') ADVANCE(148);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'u') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (lookahead == 'y') ADVANCE(129);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(aux_sym_column_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(anon_sym_text);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(anon_sym_char);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(anon_sym_varchar);
      if (lookahead == '2') ADVANCE(171);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(anon_sym_varchar2);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(anon_sym_tinyint);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(anon_sym_int);
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(anon_sym_integer);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(anon_sym_bigint);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(anon_sym_double);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(anon_sym_decimal);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(anon_sym_bool);
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(anon_sym_boolean);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(anon_sym_json);
      if (lookahead == 'b') ADVANCE(182);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(anon_sym_jsonb);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(anon_sym_clob);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(anon_sym_date);
      if (lookahead == 't') ADVANCE(53);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(anon_sym_time);
      if (lookahead == 's') ADVANCE(113);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(anon_sym_datetime);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(anon_sym_timestamp);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(anon_sym_nvarchar);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(anon_sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(anon_sym_notnull);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(anon_sym_unique);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(anon_sym_unique);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(anon_sym_default);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(anon_sym_default);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(anon_sym_increment);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(anon_sym_increment);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(anon_sym_PK);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(anon_sym_PK);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(anon_sym_pk);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(anon_sym_pk);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(anon_sym_primarykey);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(aux_sym_length_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(206);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == ')') ADVANCE(227);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(aux_sym_key_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(210);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_separate);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(anon_sym_ref);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(anon_sym_ref);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(anon_sym_note);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(anon_sym_note);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(anon_sym_Note);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(anon_sym_Note);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(166);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '>') ADVANCE(223);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(aux_sym__note_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(225);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(anon_sym_LPAREN_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 4},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 4},
  [46] = {.lex_state = 4},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 4},
  [51] = {.lex_state = 4},
  [52] = {.lex_state = 4},
  [53] = {.lex_state = 4},
  [54] = {.lex_state = 4},
  [55] = {.lex_state = 4},
  [56] = {.lex_state = 4},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 4},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 4},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 4},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 210},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 4},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 123},
  [77] = {.lex_state = 210},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 123},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 210},
  [84] = {.lex_state = 123},
  [85] = {.lex_state = 4},
  [86] = {.lex_state = 4},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 210},
  [89] = {.lex_state = 123},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_keyword_table] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_text] = ACTIONS(1),
    [anon_sym_char] = ACTIONS(1),
    [anon_sym_varchar] = ACTIONS(1),
    [anon_sym_varchar2] = ACTIONS(1),
    [anon_sym_tinyint] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_integer] = ACTIONS(1),
    [anon_sym_bigint] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_double] = ACTIONS(1),
    [anon_sym_decimal] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_boolean] = ACTIONS(1),
    [anon_sym_json] = ACTIONS(1),
    [anon_sym_jsonb] = ACTIONS(1),
    [anon_sym_clob] = ACTIONS(1),
    [anon_sym_date] = ACTIONS(1),
    [anon_sym_time] = ACTIONS(1),
    [anon_sym_datetime] = ACTIONS(1),
    [anon_sym_timestamp] = ACTIONS(1),
    [anon_sym_nvarchar] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_notnull] = ACTIONS(1),
    [anon_sym_unique] = ACTIONS(1),
    [anon_sym_default] = ACTIONS(1),
    [anon_sym_increment] = ACTIONS(1),
    [anon_sym_PK] = ACTIONS(1),
    [anon_sym_pk] = ACTIONS(1),
    [anon_sym_primarykey] = ACTIONS(1),
    [aux_sym_length_token1] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_separate] = ACTIONS(1),
    [anon_sym_ref] = ACTIONS(1),
    [anon_sym_note] = ACTIONS(1),
    [anon_sym_Note] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(68),
    [sym_table] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(38),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_keyword_table] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(9), 6,
      anon_sym_varchar,
      anon_sym_int,
      anon_sym_bool,
      anon_sym_json,
      anon_sym_date,
      anon_sym_time,
    ACTIONS(7), 29,
      anon_sym_string,
      anon_sym_text,
      anon_sym_char,
      anon_sym_varchar2,
      anon_sym_tinyint,
      anon_sym_integer,
      anon_sym_bigint,
      anon_sym_float,
      anon_sym_double,
      anon_sym_decimal,
      anon_sym_boolean,
      anon_sym_jsonb,
      anon_sym_clob,
      anon_sym_datetime,
      anon_sym_timestamp,
      anon_sym_nvarchar,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [40] = 7,
    ACTIONS(19), 1,
      anon_sym_nvarchar,
    STATE(4), 1,
      sym_type,
    ACTIONS(13), 2,
      anon_sym_char,
      anon_sym_decimal,
    ACTIONS(15), 2,
      anon_sym_varchar,
      anon_sym_int,
    STATE(10), 2,
      sym__basic_type,
      sym__type_length,
    ACTIONS(17), 4,
      anon_sym_bool,
      anon_sym_json,
      anon_sym_date,
      anon_sym_time,
    ACTIONS(11), 13,
      anon_sym_string,
      anon_sym_text,
      anon_sym_varchar2,
      anon_sym_tinyint,
      anon_sym_integer,
      anon_sym_bigint,
      anon_sym_float,
      anon_sym_double,
      anon_sym_boolean,
      anon_sym_jsonb,
      anon_sym_clob,
      anon_sym_datetime,
      anon_sym_timestamp,
  [80] = 11,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      aux_sym_column_token1,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    ACTIONS(31), 1,
      anon_sym_default,
    STATE(49), 1,
      sym_key_value,
    STATE(50), 1,
      sym_setting,
    STATE(53), 1,
      sym_setting_key,
    STATE(70), 1,
      sym_key,
    ACTIONS(29), 2,
      anon_sym_notnull,
      anon_sym_primarykey,
    ACTIONS(33), 3,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
    ACTIONS(27), 5,
      anon_sym_null,
      anon_sym_unique,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
  [121] = 8,
    ACTIONS(35), 1,
      anon_sym_RBRACK,
    ACTIONS(39), 1,
      anon_sym_default,
    STATE(11), 1,
      sym_setting_key,
    STATE(20), 1,
      sym_key_value,
    STATE(87), 1,
      sym_key,
    STATE(7), 2,
      sym_setting_keys,
      aux_sym_setting_repeat1,
    ACTIONS(41), 3,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
    ACTIONS(37), 7,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
  [155] = 4,
    STATE(47), 1,
      sym_bracket,
    ACTIONS(47), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
    ACTIONS(43), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_notnull,
      anon_sym_primarykey,
    ACTIONS(45), 10,
      aux_sym_column_token1,
      anon_sym_null,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [181] = 8,
    ACTIONS(39), 1,
      anon_sym_default,
    ACTIONS(49), 1,
      anon_sym_RBRACK,
    STATE(11), 1,
      sym_setting_key,
    STATE(20), 1,
      sym_key_value,
    STATE(87), 1,
      sym_key,
    STATE(8), 2,
      sym_setting_keys,
      aux_sym_setting_repeat1,
    ACTIONS(41), 3,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
    ACTIONS(37), 7,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
  [215] = 8,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
    ACTIONS(56), 1,
      anon_sym_default,
    STATE(11), 1,
      sym_setting_key,
    STATE(20), 1,
      sym_key_value,
    STATE(87), 1,
      sym_key,
    STATE(8), 2,
      sym_setting_keys,
      aux_sym_setting_repeat1,
    ACTIONS(59), 3,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
    ACTIONS(53), 7,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
  [249] = 2,
    ACTIONS(62), 5,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_notnull,
      anon_sym_primarykey,
      aux_sym_length_token1,
    ACTIONS(64), 10,
      aux_sym_column_token1,
      anon_sym_null,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [269] = 2,
    ACTIONS(66), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_notnull,
      anon_sym_primarykey,
    ACTIONS(68), 10,
      aux_sym_column_token1,
      anon_sym_null,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [288] = 3,
    ACTIONS(70), 1,
      anon_sym_COMMA,
    STATE(14), 1,
      aux_sym_setting_keys_repeat1,
    ACTIONS(72), 12,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [309] = 2,
    ACTIONS(74), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_notnull,
      anon_sym_primarykey,
    ACTIONS(76), 10,
      aux_sym_column_token1,
      anon_sym_null,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [328] = 6,
    ACTIONS(39), 1,
      anon_sym_default,
    STATE(19), 1,
      sym_setting_key,
    STATE(20), 1,
      sym_key_value,
    STATE(87), 1,
      sym_key,
    ACTIONS(41), 3,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
    ACTIONS(37), 7,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
  [355] = 3,
    ACTIONS(70), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_setting_keys_repeat1,
    ACTIONS(78), 12,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [376] = 2,
    ACTIONS(82), 1,
      sym_separate,
    ACTIONS(80), 13,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [395] = 3,
    ACTIONS(84), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_setting_keys_repeat1,
    ACTIONS(87), 12,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [416] = 2,
    ACTIONS(89), 4,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_notnull,
      anon_sym_primarykey,
    ACTIONS(91), 10,
      aux_sym_column_token1,
      anon_sym_null,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [435] = 1,
    ACTIONS(93), 13,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [451] = 1,
    ACTIONS(87), 13,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [467] = 1,
    ACTIONS(80), 13,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [483] = 1,
    ACTIONS(95), 13,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [499] = 1,
    ACTIONS(97), 13,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [515] = 1,
    ACTIONS(99), 13,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [531] = 1,
    ACTIONS(101), 13,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_null,
      anon_sym_notnull,
      anon_sym_unique,
      anon_sym_default,
      anon_sym_increment,
      anon_sym_PK,
      anon_sym_pk,
      anon_sym_primarykey,
      anon_sym_ref,
      anon_sym_note,
      anon_sym_Note,
  [547] = 7,
    ACTIONS(103), 1,
      aux_sym_length_token1,
    ACTIONS(107), 1,
      anon_sym_LT,
    ACTIONS(109), 1,
      anon_sym_SQUOTE,
    ACTIONS(111), 1,
      anon_sym_BQUOTE,
    STATE(18), 1,
      sym_value,
    ACTIONS(105), 3,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_LT_GT,
    STATE(21), 3,
      sym__ref,
      sym__note,
      sym__default,
  [573] = 7,
    ACTIONS(113), 1,
      aux_sym_length_token1,
    ACTIONS(117), 1,
      anon_sym_LT,
    ACTIONS(119), 1,
      anon_sym_SQUOTE,
    ACTIONS(121), 1,
      anon_sym_BQUOTE,
    STATE(51), 1,
      sym_value,
    ACTIONS(115), 3,
      anon_sym_GT,
      anon_sym_DASH,
      anon_sym_LT_GT,
    STATE(52), 3,
      sym__ref,
      sym__note,
      sym__default,
  [599] = 4,
    ACTIONS(123), 1,
      anon_sym_LBRACE,
    ACTIONS(125), 1,
      anon_sym_DOT,
    STATE(41), 1,
      sym_keyword,
    ACTIONS(127), 2,
      anon_sym_as,
      anon_sym_enum,
  [613] = 4,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    ACTIONS(131), 1,
      aux_sym_column_token1,
    STATE(3), 1,
      sym_column,
    STATE(31), 2,
      sym_body,
      aux_sym_table_repeat1,
  [627] = 4,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    ACTIONS(135), 1,
      aux_sym_column_token1,
    STATE(3), 1,
      sym_column,
    STATE(29), 2,
      sym_body,
      aux_sym_table_repeat1,
  [641] = 3,
    STATE(45), 1,
      sym_keyword,
    ACTIONS(127), 2,
      anon_sym_as,
      anon_sym_enum,
    ACTIONS(138), 2,
      anon_sym_LBRACE,
      anon_sym_DOT,
  [653] = 4,
    ACTIONS(131), 1,
      aux_sym_column_token1,
    ACTIONS(140), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      sym_column,
    STATE(29), 2,
      sym_body,
      aux_sym_table_repeat1,
  [667] = 4,
    ACTIONS(142), 1,
      aux_sym_column_token1,
    STATE(35), 1,
      sym_identifier,
    STATE(74), 1,
      sym_schema,
    STATE(75), 1,
      sym_table_name,
  [680] = 4,
    ACTIONS(142), 1,
      aux_sym_column_token1,
    STATE(27), 1,
      sym_identifier,
    STATE(72), 1,
      sym_table_name,
    STATE(74), 1,
      sym_schema,
  [693] = 1,
    ACTIONS(144), 4,
      anon_sym_LBRACE,
      anon_sym_DOT,
      anon_sym_as,
      anon_sym_enum,
  [700] = 3,
    ACTIONS(146), 1,
      anon_sym_DOT,
    STATE(41), 1,
      sym_keyword,
    ACTIONS(127), 2,
      anon_sym_as,
      anon_sym_enum,
  [711] = 4,
    ACTIONS(142), 1,
      aux_sym_column_token1,
    STATE(35), 1,
      sym_identifier,
    STATE(74), 1,
      sym_schema,
    STATE(81), 1,
      sym_table_name,
  [724] = 3,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(151), 1,
      sym_keyword_table,
    STATE(37), 2,
      sym_table,
      aux_sym_source_file_repeat1,
  [735] = 3,
    ACTIONS(5), 1,
      sym_keyword_table,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
    STATE(37), 2,
      sym_table,
      aux_sym_source_file_repeat1,
  [746] = 3,
    ACTIONS(156), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      sym_bracket,
    ACTIONS(47), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [757] = 2,
    STATE(47), 1,
      sym_bracket,
    ACTIONS(47), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [765] = 3,
    ACTIONS(142), 1,
      aux_sym_column_token1,
    STATE(48), 1,
      sym_identifier,
    STATE(66), 1,
      sym_alias,
  [775] = 2,
    STATE(17), 1,
      sym_bracket,
    ACTIONS(47), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [783] = 1,
    ACTIONS(158), 3,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [789] = 2,
    ACTIONS(82), 1,
      sym_separate,
    ACTIONS(80), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [797] = 3,
    ACTIONS(142), 1,
      aux_sym_column_token1,
    STATE(48), 1,
      sym_identifier,
    STATE(58), 1,
      sym_alias,
  [807] = 1,
    ACTIONS(160), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [812] = 2,
    ACTIONS(162), 1,
      aux_sym_length_token1,
    STATE(39), 1,
      sym_length,
  [819] = 1,
    ACTIONS(164), 2,
      anon_sym_LBRACE,
      anon_sym_DOT,
  [824] = 1,
    ACTIONS(80), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [829] = 1,
    ACTIONS(166), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [834] = 1,
    ACTIONS(93), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [839] = 1,
    ACTIONS(95), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [844] = 1,
    ACTIONS(168), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [849] = 1,
    ACTIONS(97), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [854] = 2,
    ACTIONS(170), 1,
      aux_sym_column_token1,
    STATE(57), 1,
      sym_column,
  [861] = 1,
    ACTIONS(99), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [866] = 1,
    ACTIONS(101), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [871] = 1,
    ACTIONS(172), 2,
      anon_sym_LBRACE,
      anon_sym_DOT,
  [876] = 1,
    ACTIONS(7), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [881] = 1,
    ACTIONS(174), 2,
      ts_builtin_sym_end,
      sym_keyword_table,
  [886] = 1,
    ACTIONS(176), 2,
      anon_sym_RBRACE,
      aux_sym_column_token1,
  [891] = 1,
    ACTIONS(178), 2,
      ts_builtin_sym_end,
      sym_keyword_table,
  [896] = 2,
    ACTIONS(131), 1,
      aux_sym_column_token1,
    STATE(24), 1,
      sym_column,
  [903] = 2,
    ACTIONS(162), 1,
      aux_sym_length_token1,
    STATE(42), 1,
      sym_length,
  [910] = 2,
    ACTIONS(142), 1,
      aux_sym_column_token1,
    STATE(30), 1,
      sym_identifier,
  [917] = 1,
    ACTIONS(138), 2,
      anon_sym_LBRACE,
      anon_sym_DOT,
  [922] = 1,
    ACTIONS(82), 1,
      sym_separate,
  [926] = 1,
    ACTIONS(180), 1,
      ts_builtin_sym_end,
  [930] = 1,
    ACTIONS(182), 1,
      aux_sym_key_value_token1,
  [934] = 1,
    ACTIONS(184), 1,
      sym_separate,
  [938] = 1,
    ACTIONS(186), 1,
      anon_sym_SQUOTE,
  [942] = 1,
    ACTIONS(188), 1,
      anon_sym_LBRACE,
  [946] = 1,
    ACTIONS(190), 1,
      anon_sym_LPAREN_RPAREN,
  [950] = 1,
    ACTIONS(192), 1,
      anon_sym_DOT,
  [954] = 1,
    ACTIONS(194), 1,
      anon_sym_DOT,
  [958] = 1,
    ACTIONS(196), 1,
      aux_sym__note_token1,
  [962] = 1,
    ACTIONS(198), 1,
      aux_sym_key_value_token1,
  [966] = 1,
    ACTIONS(200), 1,
      anon_sym_BQUOTE,
  [970] = 1,
    ACTIONS(202), 1,
      aux_sym__note_token1,
  [974] = 1,
    ACTIONS(204), 1,
      anon_sym_SQUOTE,
  [978] = 1,
    ACTIONS(206), 1,
      anon_sym_DOT,
  [982] = 1,
    ACTIONS(208), 1,
      anon_sym_BQUOTE,
  [986] = 1,
    ACTIONS(210), 1,
      aux_sym_key_value_token1,
  [990] = 1,
    ACTIONS(212), 1,
      aux_sym__note_token1,
  [994] = 1,
    ACTIONS(214), 1,
      aux_sym_column_token1,
  [998] = 1,
    ACTIONS(216), 1,
      anon_sym_LPAREN_RPAREN,
  [1002] = 1,
    ACTIONS(218), 1,
      sym_separate,
  [1006] = 1,
    ACTIONS(220), 1,
      aux_sym_key_value_token1,
  [1010] = 1,
    ACTIONS(222), 1,
      aux_sym__note_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 40,
  [SMALL_STATE(4)] = 80,
  [SMALL_STATE(5)] = 121,
  [SMALL_STATE(6)] = 155,
  [SMALL_STATE(7)] = 181,
  [SMALL_STATE(8)] = 215,
  [SMALL_STATE(9)] = 249,
  [SMALL_STATE(10)] = 269,
  [SMALL_STATE(11)] = 288,
  [SMALL_STATE(12)] = 309,
  [SMALL_STATE(13)] = 328,
  [SMALL_STATE(14)] = 355,
  [SMALL_STATE(15)] = 376,
  [SMALL_STATE(16)] = 395,
  [SMALL_STATE(17)] = 416,
  [SMALL_STATE(18)] = 435,
  [SMALL_STATE(19)] = 451,
  [SMALL_STATE(20)] = 467,
  [SMALL_STATE(21)] = 483,
  [SMALL_STATE(22)] = 499,
  [SMALL_STATE(23)] = 515,
  [SMALL_STATE(24)] = 531,
  [SMALL_STATE(25)] = 547,
  [SMALL_STATE(26)] = 573,
  [SMALL_STATE(27)] = 599,
  [SMALL_STATE(28)] = 613,
  [SMALL_STATE(29)] = 627,
  [SMALL_STATE(30)] = 641,
  [SMALL_STATE(31)] = 653,
  [SMALL_STATE(32)] = 667,
  [SMALL_STATE(33)] = 680,
  [SMALL_STATE(34)] = 693,
  [SMALL_STATE(35)] = 700,
  [SMALL_STATE(36)] = 711,
  [SMALL_STATE(37)] = 724,
  [SMALL_STATE(38)] = 735,
  [SMALL_STATE(39)] = 746,
  [SMALL_STATE(40)] = 757,
  [SMALL_STATE(41)] = 765,
  [SMALL_STATE(42)] = 775,
  [SMALL_STATE(43)] = 783,
  [SMALL_STATE(44)] = 789,
  [SMALL_STATE(45)] = 797,
  [SMALL_STATE(46)] = 807,
  [SMALL_STATE(47)] = 812,
  [SMALL_STATE(48)] = 819,
  [SMALL_STATE(49)] = 824,
  [SMALL_STATE(50)] = 829,
  [SMALL_STATE(51)] = 834,
  [SMALL_STATE(52)] = 839,
  [SMALL_STATE(53)] = 844,
  [SMALL_STATE(54)] = 849,
  [SMALL_STATE(55)] = 854,
  [SMALL_STATE(56)] = 861,
  [SMALL_STATE(57)] = 866,
  [SMALL_STATE(58)] = 871,
  [SMALL_STATE(59)] = 876,
  [SMALL_STATE(60)] = 881,
  [SMALL_STATE(61)] = 886,
  [SMALL_STATE(62)] = 891,
  [SMALL_STATE(63)] = 896,
  [SMALL_STATE(64)] = 903,
  [SMALL_STATE(65)] = 910,
  [SMALL_STATE(66)] = 917,
  [SMALL_STATE(67)] = 922,
  [SMALL_STATE(68)] = 926,
  [SMALL_STATE(69)] = 930,
  [SMALL_STATE(70)] = 934,
  [SMALL_STATE(71)] = 938,
  [SMALL_STATE(72)] = 942,
  [SMALL_STATE(73)] = 946,
  [SMALL_STATE(74)] = 950,
  [SMALL_STATE(75)] = 954,
  [SMALL_STATE(76)] = 958,
  [SMALL_STATE(77)] = 962,
  [SMALL_STATE(78)] = 966,
  [SMALL_STATE(79)] = 970,
  [SMALL_STATE(80)] = 974,
  [SMALL_STATE(81)] = 978,
  [SMALL_STATE(82)] = 982,
  [SMALL_STATE(83)] = 986,
  [SMALL_STATE(84)] = 990,
  [SMALL_STATE(85)] = 994,
  [SMALL_STATE(86)] = 998,
  [SMALL_STATE(87)] = 1002,
  [SMALL_STATE(88)] = 1006,
  [SMALL_STATE(89)] = 1010,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_column, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_column, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__basic_type, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__basic_type, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_setting_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_setting_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_setting_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_setting_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting_keys, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_length, 4, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type_length, 4, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting_keys, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting_key, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 1, 0, 0),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_setting_keys_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_setting_keys_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_length, 6, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type_length, 6, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value, 4, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__note, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__default, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__ref, 5, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_schema, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_table_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_table_name, 1, 0, 0), REDUCE(sym_schema, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [151] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_length, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table_name, 5, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 4, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setting, 2, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_table, 5, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dbdiagram(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "dbdiagram",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
